In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
item = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [3]:
encoder=LabelEncoder()
encoder.fit(item)
# item 안에 값을 넣어 사전을 만든다. 중복 없이 목록값만 뽑는 걸 fit에서
label = encoder.transform(item)
label

array([0, 1, 4, 5, 3, 3, 2, 2])

In [5]:
encoder.classes_ # 목록을 만든 것이 보임 # 전자레인지는 인덱스 4 # 사전처럼 가나다라순

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [6]:
encoder.inverse_transform(label)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [7]:
# 값의 크기가 차이가 나면 안되는 경우(예. 회귀는 값의 크기에 영향을 받음) 원 핫 인코딩 하나만 핫하고 나머지는 0

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [13]:
item = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
item = np.array(item).reshape(-1,1) # reshape이 리스트에 없어서 일단 배열로 바꿈

In [15]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(item)
oh_label=oh_encoder.transform(item)
oh_label.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [17]:
df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [19]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [ ]:
# 숫자의 크기가 모델에 영향을 주면 원핫인코딩

# 영향을 주지 않으면 레이블 인코딩

In [ ]:
# 피처 스케일링과 정규화
# 변수 값의 범위가 제각각일 때 ex. 중간시험 100점과 토익 100점의 의미는 굉장히 다름


In [20]:
# StandardScaler
from sklearn.datasets import load_iris
import pandas as pd

In [21]:
iris = load_iris()

In [22]:
iris_df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [23]:
# 평균이 0이고 분산이 1이 되게 바꾸기
iris_df.mean() # 평균이 0이 아님

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [24]:
iris_df.var() # 분산이 1이 아님

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()
iris_scaled=scaler.fit_transform(iris_df) # fit하고 transform 한번에

In [30]:
iris_df_scaled = pd.DataFrame(iris_scaled,columns=iris.feature_names) # 데이터프레임으로 변환

In [31]:
iris_df_scaled.mean() # 0에 가까움

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [32]:
iris_df_scaled.var() # 1에 가까움
# 원데이터보다 가우시안 정규분포를 따르는 쪽으로 감

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [33]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [34]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [ ]:
# MinMaxScaler :0에서 1사이의 값으로 맞춰줌(n에서 m 사이의 값으로 변경 가능)

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled,columns=iris.feature_names)

In [37]:
iris_df_scaled.min() # 최소값 0으로 맞춰짐

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [38]:
iris_df_scaled.max() # 최대값 1로 맞춰짐

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [41]:
train_array = np.arange(0,11).reshape(-1,1) # 0부터 10까지 
# np.arange(0,11) 일차원으로 만들어짐 reshape(-1,1) 2차원으로 만들어줌 한 행에 한 건의 데이터가 들어가게(총 10건의 데이터)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [42]:
test_array = np.arange(0,6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_array)

In [46]:
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [47]:
# scaler.fit_transform(test_array)
# train데이터의 잣대로 봐야 똑같이 바뀌는데 5가
scaler.transform(test_array)
# 학습 데이터는 한 달전에 완성됨 검증용은 이후에 완성됨 -> 뒤쪽 데이터는 또 fit하지 말고 transform만

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])